import { Country, Author, Document, Publisher } from "./types";

export const countries: Country[] = [
  { id: "1", name: "United States", documentPublished: 12 },
  { id: "2", name: "United Kingdom", documentPublished: 28 },
  { id: "3", name: "Canada", documentPublished: 7 },
  { id: "4", name: "Australia", documentPublished: 43 },
  { id: "5", name: "Germany", documentPublished: 18 },
  { id: "6", name: "France", documentPublished: 35 },
  { id: "7", name: "Brazil", documentPublished: 9 },
  { id: "8", name: "India", documentPublished: 22 },
  { id: "9", name: "China", documentPublished: 48 },
  { id: "10", name: "Japan", documentPublished: 31 },
  { id: "11", name: "South Korea", documentPublished: 5 },
  { id: "12", name: "Mexico", documentPublished: 40 },
  { id: "13", name: "Italy", documentPublished: 14 },
  { id: "14", name: "Spain", documentPublished: 37 },
  { id: "15", name: "Russia", documentPublished: 3 },
  { id: "16", name: "South Africa", documentPublished: 29 },
  { id: "17", name: "Argentina", documentPublished: 13 },
  { id: "18", name: "New Zealand", documentPublished: 47 },
  { id: "19", name: "Netherlands", documentPublished: 8 },
  { id: "20", name: "Switzerland", documentPublished: 25 },
  { id: "21", name: "Sweden", documentPublished: 42 },
  { id: "22", name: "Norway", documentPublished: 10 },
  { id: "23", name: "Singapore", documentPublished: 36 },
  { id: "24", name: "Malaysia", documentPublished: 15 },
  { id: "25", name: "Thailand", documentPublished: 38 },
  { id: "26", name: "Egypt", documentPublished: 6 },
  { id: "27", name: "Nigeria", documentPublished: 33 },
  { id: "28", name: "Kenya", documentPublished: 2 },
  { id: "29", name: "Ghana", documentPublished: 27 },
  { id: "30", name: "Saudi Arabia", documentPublished: 19 },
  { id: "31", name: "United Arab Emirates", documentPublished: 44 },
  { id: "32", name: "Qatar", documentPublished: 11 },
  { id: "33", name: "Turkey", documentPublished: 46 },
  { id: "34", name: "Pakistan", documentPublished: 24 },
  { id: "35", name: "Bangladesh", documentPublished: 4 },
  { id: "36", name: "Indonesia", documentPublished: 30 },
  { id: "37", name: "Vietnam", documentPublished: 16 },
  { id: "38", name: "Philippines", documentPublished: 41 },
  { id: "39", name: "Chile", documentPublished: 20 },
  { id: "40", name: "Colombia", documentPublished: 39 },
  { id: "41", name: "Peru", documentPublished: 23 },
  { id: "42", name: "Ecuador", documentPublished: 45 },
  { id: "43", name: "Venezuela", documentPublished: 1 },
  { id: "44", name: "Cuba", documentPublished: 34 },
  { id: "45", name: "Jamaica", documentPublished: 0 },
  { id: "46", name: "Trinidad and Tobago", documentPublished: 26 },
  { id: "47", name: "South Sudan", documentPublished: 49 },
  { id: "48", name: "Ethiopia", documentPublished: 17 },
  { id: "49", name: "Morocco", documentPublished: 32 },
  { id: "50", name: "Algeria", documentPublished: 21 },
  { id: "51", name: "Tunisia", documentPublished: 5 },
  { id: "52", name: "Greece", documentPublished: 40 },
  { id: "53", name: "Portugal", documentPublished: 14 },
  { id: "54", name: "Ireland", documentPublished: 37 },
  { id: "55", name: "Austria", documentPublished: 3 },
  { id: "56", name: "Belgium", documentPublished: 29 },
  { id: "57", name: "Nigeria", documentPublished: 13 },
  { id: "58", name: "Poland", documentPublished: 28 },
  { id: "59", name: "Romania", documentPublished: 8 },
  { id: "60", name: "Hungary", documentPublished: 43 },
];

export const publishers: Publisher[] = [
  { id: "1", name: "Publisher A", country: countries[0] },
  { id: "2", name: "Publisher B", country: countries[1] },
  { id: "3", name: "Publisher C", country: countries[2] },
  { id: "4", name: "Publisher D", country: countries[3] },
  { id: "5", name: "Publisher E", country: countries[4] },
  { id: "6", name: "Publisher F", country: countries[5] },
  { id: "7", name: "Publisher G", country: countries[6] },
  { id: "8", name: "Publisher H", country: countries[7] },
  { id: "9", name: "Publisher I", country: countries[8] },
  { id: "10", name: "Publisher J", country: countries[9] },
  { id: "11", name: "Publisher K", country: countries[10] },
  { id: "12", name: "Publisher L", country: countries[11] },
  { id: "13", name: "Publisher M", country: countries[12] },
  { id: "14", name: "Publisher N", country: countries[13] },
  { id: "15", name: "Publisher O", country: countries[14] },
  { id: "16", name: "Publisher P", country: countries[15] },
  { id: "17", name: "Publisher Q", country: countries[16] },
  { id: "18", name: "Publisher R", country: countries[17] },
  { id: "19", name: "Publisher S", country: countries[18] },
  { id: "20", name: "Publisher T", country: countries[19] },
  { id: "21", name: "Publisher U", country: countries[20] },
  { id: "22", name: "Publisher V", country: countries[21] },
  { id: "23", name: "Publisher W", country: countries[22] },
  { id: "24", name: "Publisher X", country: countries[23] },
  { id: "25", name: "Publisher Y", country: countries[24] },
  { id: "26", name: "Publisher Z", country: countries[25] },
  { id: "27", name: "Publisher AA", country: countries[26] },
  { id: "28", name: "Publisher BB", country: countries[27] },
  { id: "29", name: "Publisher CC", country: countries[28] },
  { id: "30", name: "Publisher DD", country: countries[29] },
  { id: "31", name: "Publisher EE", country: countries[30] },
  { id: "32", name: "Publisher FF", country: countries[31] },
  { id: "33", name: "Publisher GG", country: countries[32] },
  { id: "34", name: "Publisher HH", country: countries[33] },
  { id: "35", name: "Publisher II", country: countries[34] },
  { id: "36", name: "Publisher JJ", country: countries[35] },
  { id: "37", name: "Publisher KK", country: countries[36] },
  { id: "38", name: "Publisher LL", country: countries[37] },
  { id: "39", name: "Publisher MM", country: countries[38] },
  { id: "40", name: "Publisher NN", country: countries[39] },
  { id: "41", name: "Publisher OO", country: countries[40] },
  { id: "42", name: "Publisher PP", country: countries[41] },
  { id: "43", name: "Publisher QQ", country: countries[42] },
  { id: "44", name: "Publisher RR", country: countries[43] },
  { id: "45", name: "Publisher SS", country: countries[44] },
  { id: "46", name: "Publisher TT", country: countries[45] },
  { id: "47", name: "Publisher UU", country: countries[46] },
  { id: "48", name: "Publisher VV", country: countries[47] },
  { id: "49", name: "Publisher WW", country: countries[48] },
  { id: "50", name: "Publisher XX", country: countries[49] },
  { id: "51", name: "Publisher YY", country: countries[50] },
  { id: "52", name: "Publisher ZZ", country: countries[51] },
  { id: "53", name: "Publisher AAA", country: countries[52] },
  { id: "54", name: "Publisher BBB", country: countries[53] },
  { id: "55", name: "Publisher CCC", country: countries[54] },
  { id: "56", name: "Publisher DDD", country: countries[55] },
  { id: "57", name: "Publisher EEE", country: countries[56] },
  { id: "58", name: "Publisher FFF", country: countries[57] },
  { id: "59", name: "Publisher GGG", country: countries[58] },
  { id: "60", name: "Publisher HHH", country: countries[59] },
];

export const authors: Author[] = [
  { id: "1", firstName: "John", lastName: "Doe" },
  { id: "2", firstName: "Jane", lastName: "Smith" },
  { id: "3", firstName: "Robert", lastName: "Johnson" },
  { id: "4", firstName: "Emily", lastName: "Williams" },
  { id: "5", firstName: "Michael", lastName: "Brown" },
  { id: "6", firstName: "Amanda", lastName: "Jones" },
  { id: "7", firstName: "Daniel", lastName: "Miller" },
  { id: "8", firstName: "Olivia", lastName: "Davis" },
  { id: "9", firstName: "William", lastName: "Martinez" },
  { id: "10", firstName: "Sophia", lastName: "Garcia" },
  { id: "11", firstName: "Ethan", lastName: "Lee" },
  { id: "12", firstName: "Mia", lastName: "Clark" },
  { id: "13", firstName: "David", lastName: "Lopez" },
  { id: "14", firstName: "Emma", lastName: "Taylor" },
  { id: "15", firstName: "Liam", lastName: "Moore" },
  { id: "16", firstName: "Ava", lastName: "Wright" },
  { id: "17", firstName: "Matthew", lastName: "Hall" },
  { id: "18", firstName: "Isabella", lastName: "Allen" },
  { id: "19", firstName: "Christopher", lastName: "Young" },
  { id: "20", firstName: "Amelia", lastName: "Turner" },
  { id: "21", firstName: "Elijah", lastName: "Adams" },
  { id: "22", firstName: "Sofia", lastName: "Hill" },
  { id: "23", firstName: "Andrew", lastName: "Evans" },
  { id: "24", firstName: "Abigail", lastName: "Perez" },
  { id: "25", firstName: "Nathan", lastName: "Gomez" },
  { id: "26", firstName: "Madison", lastName: "Parker" },
  { id: "27", firstName: "Logan", lastName: "Carter" },
  { id: "28", firstName: "Grace", lastName: "Baker" },
  { id: "29", firstName: "James", lastName: "Flores" },
  { id: "30", firstName: "Lily", lastName: "Butler" },
  { id: "31", firstName: "Benjamin", lastName: "Cooper" },
  { id: "32", firstName: "Zoe", lastName: "Murphy" },
  { id: "33", firstName: "Jackson", lastName: "Hernandez" },
  { id: "34", firstName: "Natalie", lastName: "Scott" },
  { id: "35", firstName: "Caleb", lastName: "Barnes" },
  { id: "36", firstName: "Victoria", lastName: "Green" },
  { id: "37", firstName: "Gabriel", lastName: "Robinson" },
  { id: "38", firstName: "Avery", lastName: "Fisher" },
  { id: "39", firstName: "Dylan", lastName: "Ramirez" },
  { id: "40", firstName: "Ella", lastName: "Reed" },
  { id: "41", firstName: "Nicholas", lastName: "Ward" },
  { id: "42", firstName: "Hannah", lastName: "Sanders" },
  { id: "43", firstName: "Mason", lastName: "Cruz" },
  { id: "44", firstName: "Addison", lastName: "Stewart" },
  { id: "45", firstName: "Sebastian", lastName: "Morales" },
  { id: "46", firstName: "Layla", lastName: "Simmons" },
  { id: "47", firstName: "Wyatt", lastName: "Woods" },
  { id: "48", firstName: "Harper", lastName: "Kim" },
  { id: "49", firstName: "Luke", lastName: "Luna" },
  { id: "50", firstName: "Chloe", lastName: "Harrison" },
  { id: "51", firstName: "Isaac", lastName: "Gordon" },
  { id: "52", firstName: "Brooklyn", lastName: "Kennedy" },
  { id: "53", firstName: "Landon", lastName: "Richardson" },
  { id: "54", firstName: "Peyton", lastName: "Nguyen" },
  { id: "55", firstName: "Grayson", lastName: "Chavez" },
  { id: "56", firstName: "Scarlett", lastName: "Shaw" },
  { id: "57", firstName: "Jaxon", lastName: "Hansen" },
  { id: "58", firstName: "Aria", lastName: "Ferguson" },
  { id: "59", firstName: "Leo", lastName: "Pearson" },
  { id: "60", firstName: "Evelyn", lastName: "Armstrong" },
];

export const documents: Document[] = [
  {
    id: "1",
    title: "Document 1",
    publisher: publishers[0],
    author: authors[0],
  },
  {
    id: "2",
    title: "Document 2",
    publisher: publishers[1],
    author: authors[1],
  },
  {
    id: "3",
    title: "Document 3",
    publisher: publishers[2],
    author: authors[2],
  },
  {
    id: "4",
    title: "Document 4",
    publisher: publishers[3],
    author: authors[3],
  },
  {
    id: "5",
    title: "Document 5",
    publisher: publishers[4],
    author: authors[4],
  },
  {
    id: "6",
    title: "Document 6",
    publisher: publishers[5],
    author: authors[5],
  },
  {
    id: "7",
    title: "Document 7",
    publisher: publishers[6],
    author: authors[6],
  },
  {
    id: "8",
    title: "Document 8",
    publisher: publishers[7],
    author: authors[7],
  },
  {
    id: "9",
    title: "Document 9",
    publisher: publishers[8],
    author: authors[8],
  },
  {
    id: "10",
    title: "Document 10",
    publisher: publishers[9],
    author: authors[9],
  },
  {
    id: "11",
    title: "Document 11",
    publisher: publishers[10],
    author: authors[10],
  },
  {
    id: "12",
    title: "Document 12",
    publisher: publishers[11],
    author: authors[11],
  },
  {
    id: "13",
    title: "Document 13",
    publisher: publishers[12],
    author: authors[12],
  },
  {
    id: "14",
    title: "Document 14",
    publisher: publishers[13],
    author: authors[13],
  },
  {
    id: "15",
    title: "Document 15",
    publisher: publishers[14],
    author: authors[14],
  },
  {
    id: "16",
    title: "Document 16",
    publisher: publishers[15],
    author: authors[15],
  },
  {
    id: "17",
    title: "Document 17",
    publisher: publishers[16],
    author: authors[16],
  },
  {
    id: "18",
    title: "Document 18",
    publisher: publishers[17],
    author: authors[17],
  },
  {
    id: "19",
    title: "Document 19",
    publisher: publishers[18],
    author: authors[18],
  },
  {
    id: "20",
    title: "Document 20",
    publisher: publishers[19],
    author: authors[19],
  },
  {
    id: "21",
    title: "Document 21",
    publisher: publishers[20],
    author: authors[20],
  },
  {
    id: "22",
    title: "Document 22",
    publisher: publishers[21],
    author: authors[21],
  },
  {
    id: "23",
    title: "Document 23",
    publisher: publishers[22],
    author: authors[22],
  },
  {
    id: "24",
    title: "Document 24",
    publisher: publishers[23],
    author: authors[23],
  },
  {
    id: "25",
    title: "Document 25",
    publisher: publishers[24],
    author: authors[24],
  },
  {
    id: "26",
    title: "Document 26",
    publisher: publishers[25],
    author: authors[25],
  },
  {
    id: "27",
    title: "Document 27",
    publisher: publishers[26],
    author: authors[26],
  },
  {
    id: "28",
    title: "Document 28",
    publisher: publishers[27],
    author: authors[27],
  },
  {
    id: "29",
    title: "Document 29",
    publisher: publishers[28],
    author: authors[28],
  },
  {
    id: "30",
    title: "Document 30",
    publisher: publishers[29],
    author: authors[29],
  },
  {
    id: "31",
    title: "Document 31",
    publisher: publishers[30],
    author: authors[30],
  },
  {
    id: "32",
    title: "Document 32",
    publisher: publishers[31],
    author: authors[31],
  },
  {
    id: "33",
    title: "Document 33",
    publisher: publishers[32],
    author: authors[32],
  },
  {
    id: "34",
    title: "Document 34",
    publisher: publishers[33],
    author: authors[33],
  },
  {
    id: "35",
    title: "Document 35",
    publisher: publishers[34],
    author: authors[34],
  },
  {
    id: "36",
    title: "Document 36",
    publisher: publishers[35],
    author: authors[35],
  },
  {
    id: "37",
    title: "Document 37",
    publisher: publishers[36],
    author: authors[36],
  },
  {
    id: "38",
    title: "Document 38",
    publisher: publishers[37],
    author: authors[37],
  },
  {
    id: "39",
    title: "Document 39",
    publisher: publishers[38],
    author: authors[38],
  },
  {
    id: "40",
    title: "Document 40",
    publisher: publishers[39],
    author: authors[39],
  },
  {
    id: "41",
    title: "Document 41",
    publisher: publishers[40],
    author: authors[40],
  },
  {
    id: "42",
    title: "Document 42",
    publisher: publishers[41],
    author: authors[41],
  },
  {
    id: "43",
    title: "Document 43",
    publisher: publishers[42],
    author: authors[42],
  },
  {
    id: "44",
    title: "Document 44",
    publisher: publishers[43],
    author: authors[43],
  },
  {
    id: "45",
    title: "Document 45",
    publisher: publishers[44],
    author: authors[44],
  },
  {
    id: "46",
    title: "Document 46",
    publisher: publishers[45],
    author: authors[45],
  },
  {
    id: "47",
    title: "Document 47",
    publisher: publishers[46],
    author: authors[46],
  },
  {
    id: "48",
    title: "Document 48",
    publisher: publishers[47],
    author: authors[47],
  },
  {
    id: "49",
    title: "Document 49",
    publisher: publishers[48],
    author: authors[48],
  },
  {
    id: "50",
    title: "Document 50",
    publisher: publishers[49],
    author: authors[49],
  },
  {
    id: "51",
    title: "Document 51",
    publisher: publishers[50],
    author: authors[50],
  },
  {
    id: "52",
    title: "Document 52",
    publisher: publishers[51],
    author: authors[51],
  },
  {
    id: "53",
    title: "Document 53",
    publisher: publishers[52],
    author: authors[52],
  },
  {
    id: "54",
    title: "Document 54",
    publisher: publishers[53],
    author: authors[53],
  },
  {
    id: "55",
    title: "Document 55",
    publisher: publishers[54],
    author: authors[54],
  },
];
